### PR TITLE
Handle concurrent scale commands

### LINKED ISSUE #253: Reset tasks count for states that are no longer desired.
## Assumptions
- Current desired state of **0.2.58**
- Delta is automatically tagging and scaling
- 4 EC2 instances are backing the project cluster
- 2 instances are used per scales state / running version of the project

## Steps to reproduce

1. Merge to master. **0.2.59** is tagged and a docker image is building
1. Wait for delta to issue scale up of **0.2.59**
1. Merge to master again before scaling task for **0.2.59** is complete. **0.2.60** is tagged and a docker image is building
1. Wait for delta to issue scale up of **0.2.60**
1. Merge to master again before scaling task for **0.2.60** is complete. **0.2.61** is tagged.

At this point the _current state_ is still **0.2.58**. Current state is **0.2.60**. ECS has three versions of the project set to run 2 tasks each totaling 6.

- **0.2.58** is taking up 2 instances
- **0.2.59** is taking up 2 instances
- **0.2.60** has no resources available.

The project is now stuck and will never successfully scale new states.

## Expected behavior

Delta automatically scales down any services that are not the desired state or the current state.

### PR DESCRIPTION
**Pull request by mbryzek**
- When there are multiple builds in set desired state,
        rollback cluster to earliest known state
      - From there scale up to the latest desired state
      - Fixes #253

### CODE REVIEW

File: api/app/actors/functions/Deployer.scala [hunk 1]
```diff
@@ -3,25 +3,53 @@ package io.flow.delta.actors.functions
...
+      case versions => scaleDown(versions)
+    }
+  }
+
+  private[this] def extras(): Seq[Version] = {
+    val allVersions = last.versions ++ desired.versions
+
+    Seq(
+      last.versions.headOption.map(_.name),
+      desired.versions.lastOption.map(_.name)
```
Comment (paololim) [inline api/app/actors/functions/Deployer.scala]: will desired state ever have more than one version?

File: api/test/actors/functions/DeployerSpec.scala [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+      SupervisorResult.Change("Desired state changed to: 0.0.3: 2 instances")
+    )
+
+    Deployer(build, last(build), desired(build)).scale() must be(
+      SupervisorResult.Change(s"Scale Down Extras: 0.0.2: Remove 2 instances")
+    )
+    setLastStates(build, Seq(Version("0.0.1", 2)))
+
+    Deployer(build, last(build), desired(build)).scale() must be(
+      SupervisorResult.Change(s"Scale Up: 0.0.3: Add 2 instances")
```
Comment (paololim) [inline api/test/actors/functions/DeployerSpec.scala]: The test seems like it is the desired behavior, so i think it is worth a try

File: api/app/actors/functions/Deployer.scala (hunk 1 above)
Comment (mbryzek) [inline api/app/actors/functions/Deployer.scala]: At the moment, for how we use delta, no - desired state is always set to the latest tag.

Over time, this is where I think we start to play with desired states of "0.0.12: 50%, 0.0.13: 50%" - but given we are not in a place to manage traffic yet, suggest we proceed with this approach for now, and add in % based management later.
